# Generated by Django 5.2.4 on 2025-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popayan_all_tour1', '0004_iglesias'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de Cloudinary (se genera automáticamente)', null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='iglesias',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='museos',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hoteles/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='iglesias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='museos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='museos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/', verbose_name='Imagen'),
        ),
    ]
