# Generated by Django 5.2.4 on 2025-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popayan_all_tour1', '0005_hotel_imagen_url_iglesias_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='direccion',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Dirección Hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='horario_aten',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Horario Hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iglesias',
            name='direccion',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Dirección Iglesia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iglesias',
            name='horario_aten',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Horario Iglesia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museos',
            name='direccion',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Dirección Museo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museos',
            name='horario_aten',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Horario Museo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='direccion',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Dirección Restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario_aten',
            field=models.TextField(default='Disponible', max_length=200, verbose_name='Horario Restaurante'),
            preserve_default=False,
        ),
    ]
