# Generated by Django 5.2.4 on 2025-12-09 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('popayan_all_tour1', '0006_hotel_direccion_hotel_horario_aten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_visitante', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita a Establecimiento',
                'verbose_name_plural': 'Visitas a Establecimientos',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
